### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by minoring**

### CODE REVIEW

**Comment by minoring** [comment]
MIT license to keep my copyright notice intact when they repurpose, redistribute, or otherwise reuse my code.

**Comment by minoring** [comment]
Duplicate of #3

**Comment by mtnviewlab** [comment]
@minoring Can you also add copyright light in the beginning of API.md as well.

**Comment by minoring** [comment]
@mtnviewlab Done. Added copyright to API.md

**Pull request merged**
